#include <stdio.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_sleep.h"
#include "esp_log.h"
#include "driver/gpio.h"
#include "ulp_lp_core.h"

static const char *TAG = "AMP_WATCHER";
#define WAKE_PIN GPIO_NUM_4

// These variables are magically generated by CMake pointing to your compiled LP Core binary!
extern const uint8_t ulp_main_bin_start[] asm("_binary_ulp_app_bin_start");
extern const uint8_t ulp_main_bin_end[]   asm("_binary_ulp_app_bin_end");

static void start_ulp_program(void) {
    ESP_LOGI(TAG, "Loading LP Core Firmware...");
    
    // 1. Configure the hardware pin (Standard GPIO configuration)
    gpio_config_t io_conf = {
        .intr_type = GPIO_INTR_DISABLE,
        .mode = GPIO_MODE_INPUT,
        .pin_bit_mask = (1ULL << WAKE_PIN),
        .pull_down_en = 0,
        .pull_up_en = 1, // Keep it HIGH until you touch it to GND
    };
    gpio_config(&io_conf);

    // 2. Load the binary into the LP Core memory
    ulp_lp_core_cfg_t cfg = {
        .wakeup_source = ULP_LP_CORE_WAKEUP_SOURCE_HP_CPU,
    };
    ESP_ERROR_CHECK(ulp_lp_core_load_binary(ulp_main_bin_start, (ulp_main_bin_end - ulp_main_bin_start)));
    
    // 3. Start the Night Watchman
    ESP_ERROR_CHECK(ulp_lp_core_run(&cfg));
    ESP_LOGI(TAG, "Night Watchman (LP Core) is active. Main CPU going to sleep.");
}

void app_main(void) {
    // Delay to let the USB CDC reconnect
    vTaskDelay(pdMS_TO_TICKS(2000));

    esp_sleep_wakeup_cause_t cause = esp_sleep_get_wakeup_cause();

    if (cause == ESP_SLEEP_WAKEUP_ULP) {
        // The LP Core woke us up!
        ESP_LOGE(TAG, "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!");
        ESP_LOGE(TAG, " ALARM TRIGGERED! LP CORE DETECTED DROP! ");
        ESP_LOGE(TAG, "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!");
        
        vTaskDelay(pdMS_TO_TICKS(5000));
        ESP_LOGI(TAG, "Resetting system...");
    } else {
        ESP_LOGI(TAG, "--- COLD BOOT ---");
    }

    start_ulp_program();

    // Tell the power manager that the LP core is allowed to wake us up
    ESP_ERROR_CHECK(esp_sleep_enable_ulp_wakeup());

    // Kill the Main CPU
    esp_deep_sleep_start();
}